### ISSUE TITLE
Target requires two new fields in tidal v1.7

### ISSUE THREAD

**Issue by isyuck** [tgirod/redirt#2]
in 1.7 I get an error without `oBusPort` and `oHandshake` being set in Target's fields. I fixed it by setting them to `Nothing` and `False` respectively. I guess this is related to the bus updates in 1.7... 

also - thanks for this! I've just started using renoise (my first daw!) with tidal, so I appreciate not having to write this file myself aha!

**Comment by tgirod** [comment]
thanks for the feedback, fixing this! I haven't been using redirt lately, but I might get back to it at some point.

**Comment by tgirod** [comment]
fixed in commit 05a6193542431e937c02d39318f0ab7e7b9aacb4
